#!/bin/bash

#SBATCH --get-user-env
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=0:05:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1

module purge
module load hpc-sdk

# here you could use for virtual environment
pip install virtualenv
virtualenv $HOME/venv/cluster-tutorial
source $HOME/venv/cluster-tutorial/bin/activate
pip install torch

# torch information
python -c "import torch; print(*torch.__config__.show().split('\n'), sep='\n')"
# run benchmark
python pytorch_bench.py > bench_results

exit 0

