#!/bin/bash

#SBATCH --get-user-env
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50000
#SBATCH --time=2-00:00:00 
#SBATCH --job-name=notebook
#SBATCH --partition=imxcluster-08

# here you could use for virtual environment
pip install virtualenv
virtualenv $HOME/venv/cluster-tutorial
source $HOME/venv/cluster-tutorial/bin/activate
pip install jupyter-notebook

jupyter notebook --no-browser -ip=0.0.0.0 --port=8889
